#!/bin/bash
cpaneluser=$1
sed "s/CPANELUSER/${cpaneluser}/g" /usr/local/etc/php-fpm.conf.default > /usr/local/etc/php-fpm-${cpaneluser}.conf
sed "s/CPANELUSER/${cpaneluser}/g" /opt/cpfpm/defaultconfs/php-fpm.pool.default > /opt/cpfpm/php-fpm.pool.d/${cpaneluser}.conf
if [ ! -d "/home/${cpaneluser}/usr/share/zoneinfo" ]; then
mkdir -p /home/${cpaneluser}/usr/share
\cp -rf /usr/share/zoneinfo  /home/${cpaneluser}/usr/share/
fi
/etc/init.d/php-fpm-${cpaneluser} reload
exit 0
